### ISSUE TITLE
Use Content Switcher on Menu Pages

### ISSUE THREAD

**Issue by aMytho** [aMytho/brave-frontier-godot#13]
We can use `res://Common/UI/ContentSwitcher/content_switcher.tscn` on the unit menus. The new content switcher was originally based off of the unit menus at `res://Menu/MenuContent.gd`. We can use the new scene and remove the old scene for re-usability.

**Comment by Iruuka** [comment]
Hello @aMytho !

I've created a PR for this Issue right here ==> https://github.com/aMytho/brave-frontier-godot/pull/19
If you have time to look at it, feel free ! (I don't think it is a prior Issue so don't loose time if you are on another Issue).

I didn't delete the MenuContent.gd yet. If I should delete it in this PR, let me know !

Have a good day/night !

**Comment by aMytho** [comment]
Merged in #19
Now that they use the content switcher, we just need to build the remaining pages.
