### ISSUE TITLE
Setup Turn/Battle System

### ISSUE THREAD

**Issue by aMytho** [aMytho/brave-frontier-godot#16]
I've been passively working on this feature. At the moment, each unit can "attack" (no target or HP system yet), and then move to the next turn. The enemy units attack, and control returns to the player. There are a lot of things to add!

Current Demo: https://github.com/aMytho/brave-frontier-godot/assets/58316242/7d309122-6135-46b1-b69d-f8f68f89ce58

I still need to add:
- Wait for animation to end before starting next turn
- Enemy AI (6 Selenas simultaneously attacking is scary)
- Battle System (HP, Atk/Def, possible sparks/crits)
- Add targeting
- Emit events when the battle is lost or won

**Comment by Iruuka** [comment]
Hello @aMytho !

I was looking at your PR (#17) and was wondering if the units stats were already available in fight ?
It doesn't look like it but I might see it wrong.
Can you confirm or refute my analysis ?

I wanted to try to work at the fighting and see if I can do something about it.
Do you think you'll add the stats soon ?
- If Yes, will you take this side of the fight development too ? Or can I try myself on it ?
- If No, can I try to add them and develop the fighting ? (if possible, I'd like to create an Issue to discuss about it if I can have this part)

Have a good Day/Night !

**Comment by aMytho** [comment]
The data is available.
- `Battle/battle.gd` has a `units` property which contains the player's units. Each unit has its stat values.
- Within `battle.gd`, `zone.stage[some_stage_index].monsters` contains the enemy units. It is updated each stage. See `res://Area/Zones/zone_base.gd` and `res://Area/Stages/stage_base.gd`

In the future we will need to override the unit data with stats from the database. However, that can wait until we are able to modify units.

I was going to add more features in #17 , but it has become a pretty big PR. I plan to add a function to end the turn for development purposes and then I'll merge it. Do you think the current state of it is readable? Its functional, but I wonder if it could be simplified.

Once that is merged, you can try making a battle system. Feel free to make an issue so we can discuss it. Most of what is needed is in the `Battle` directory. We can load real zones/stages, so you can simply create whatever you need for testing purposes. `res://Area/Areas/Mistral/AdventurePrairie/` has the current examples. All units have to have an `Attack` animation. I've based the turns on that.

**Comment by Iruuka** [comment]
Hello @aMytho !
In my opinion, I think your code is fine. Maybe I didn't touch it a lot yet so I might not see any problem with it.
You can merge. It is functional and understandable easily (for me, I need to play with the code a bit before understand it)

**Comment by aMytho** [comment]
Continued in #20
