### ISSUE TITLE
Add wait time before switching to next stage

### ISSUE THREAD

**Issue by Iruuka** [aMytho/brave-frontier-godot#24]
For now, when you're fighting units and killed the last one of a scenery, here's what is done : 
- The last enemy usit that was alive didn't fade away. They stay in place
- The unit of the next stage are loaded
- The view of the loading stage is shown

And for most part, the units are loaded a second before the view is changed.

My point here is we should add some wait time : 
- Wait until the last enemy's units are dead. That way, the unit disappear of the stage and we can progress in the next stage
- Before loading the next unit scene, we should wait the end of the loading view
- Then we fade in the enemy's units

**Comment by aMytho** [comment]
I agree, waiting a little bit would look better. When we add the death animations, we can listen for the `animation_complete` (something like that) signal. Once all enemies have emitted that, we can move to the next stage.

When we get to items and currency, we will have to wait for the collection animations as well.

**Comment by aMytho** [comment]
Do you want me to try adding the death animations? I'm assuming this was done with their animation SAM files. I don't have that software so it will have to be manually recreated. I've never worked with shaders, but I'd be willing to give it a try. Its possible we don't need shaders and it can be done with a simple opacity fade and animation player.

**Comment by Iruuka** [comment]
If you already have an idea for it, you can take this issue !
I juste create those because I was thinking they were needed. But everyone can take an issue. Maybe we need to ask you to assign us to the issue ? (I can't in my side so maybe because it's your repository  you have the access to)

**Comment by aMytho** [comment]
I'll see if I can replicate the animation. I just need to allow the user to remove a unit in `manage-squad`, and I can start it.

**Comment by aMytho** [comment]
I made some progress on this, should have a PR tomorrow.

**Comment by aMytho** [comment]
Made a PR #32 for the basic animation.

I don't have the shatter/split effect yet, that will likely require a custom shader. At the moment the unit fades (opacity), shrinks, and shakes from side to side.

**Comment by aMytho** [comment]
I added a slight delay after the turn and changed it to only load the next units once the transition is showing, rather than immediately after all units have been defeated.

Demo:
[output.webm](https://github.com/aMytho/brave-frontier-godot/assets/58316242/d2ea487a-d486-466c-a042-eab134e27e07)
