### ISSUE TITLE
Add Base stats and Live stats in fight

### ISSUE THREAD

**Issue by Iruuka** [aMytho/brave-frontier-godot#26]
For now, when fighting, we will use the ATK and HP directly from the resource of a unit to make them fight. I believe this way is wrong because we can't know, after a turn, what was the original value or the max value (like for HP) (all on me and #21)

After looking a bit, I've found the `res://Battle/UI/unit.gd`, which have the unit stat saved in it.

So maybe, we can use this resource to update the HP of a unit. This way, we would be able to even update the HP/HP mark of a unit in fight. (same goes for the monsters and their red health bar.
![image](https://github.com/aMytho/brave-frontier-godot/assets/55134997/f4cf548d-cc16-4c73-8424-b8b5adf2d28b)

**Comment by Iruuka** [comment]
Hello @aMytho,

Can you asign me this Issue ?
I'll try to take care of this one

Have a good day/night !

**Comment by Iruuka** [comment]
A quick insight of the work ==> https://drive.google.com/file/d/1DZ9kEQwvnwTTr39umLgjU7sFloHG_WrR/view?usp=sharing
This is not too fancy. But it's working. Now let's go to the enemy data.
I might update the battle_ui.tscn to save enemy's number shown. So when attacking an enemy, we would send the updated value of the enemy's HP + their ID. If their ID correspond to the one shown, we would update the health bar and %HP.

**Comment by Iruuka** [comment]
Hello @aMytho,

A PR is available for this issue ==> https://github.com/aMytho/brave-frontier-godot/pull/31/files

The % of HP of the enemy unit out of the question, do you see anything more to add in this feature ?

Edit : Have a good day/night !

**Comment by aMytho** [comment]
I think it is enough for now. Eventually, we will need to add the defend/BB bursts stats but that can wait until they are implemented. Merged in #31
