### ISSUE TITLE
Set up Dialogue, Stage Loading from Level Select

### ISSUE THREAD

**Issue by aMytho** [aMytho/brave-frontier-godot#8]
We need to setup the loading for real levels. At the moment, we are able to load the units for a stage. The info needs to be passed to the battle scenes. We will load the dialogue, stages, and cutscenes.

I have a system for loading dialogue, but a Godot resources bug has prevented it from working. Is supposed to allow us to drag and drop dialogue resources straight into the scene. Its very convenient, but the bug prevents specifying which resource type is inserted into the scene. I'll see if it has been fixed. If it hasn't, we should be able to specify any resource and work from that.

**Comment by Iruuka** [comment]
Do you already have an idea on how to proceed each round and summon enemi's unit ?

**Comment by aMytho** [comment]
Yes. The stages.gd contains the enemies and any mimics if they exist. Look in the area/stages folder for the base file. See [this file](https://github.com/aMytho/brave-frontier-godot/blob/main/Area/Areas/Mistral/AdventurePrairie/Zones/Stages/1.tres) for a basic example (contains a placeholder unit ATM).

We can make more of these resources to make each stage. It probably needs more stats, but we can potentially set stage bonuses (bonus zel, units, etc) per stage. As with the other formats, its a simple drag/drop to make each resource.

**Comment by aMytho** [comment]
This was completed.

The dialogue system needs some adjustments, but the loading of the dialogue from the level select works fine. I've been testing godot 4.1 beta 1 and it has the fixes we need for the dialogue system.
