### ISSUE TITLE
DIsplay account units on start page

### ISSUE THREAD

**Issue by aMytho** [aMytho/brave-frontier-godot#9]
Since we have a database set up, we can load the account's real units on the home page. This should be fairly straightforward.

Load the character's full sprite and display the appropriate element. We can use the Database singleton to make the appropriate query. We will need to setup a proper teams DB table at some point.

**Comment by aMytho** [comment]
May need to wait until #10 is completed. I thought these migrations were already added.

**Comment by aMytho** [comment]
This should be possible now. You can use the database class to query the teams, pick the first (or one at random), use the ResourceLookups to get the unit images, and display them. Shouldn't be too difficult.

**Comment by Iruuka** [comment]
Hello @aMytho !
I've done a first draft for this topic here ==> https://github.com/aMytho/brave-frontier-godot/pull/18
There're still some problem (which doesn't stop the game from working but are visual problem)

You can have all the information in the commit (with an actual visual in drive)

**Comment by aMytho** [comment]
Completed in #18
